kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: docker build
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      PASS:
        from_secret: PASS
    commands:
      - docker build -t fmnx.io/core/pack:latest .
      - docker login -u dancheg97 -p $PASS fmnx.io
      - docker push fmnx.io/core/pack:latest

  - name: push github mirror
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: git@github.com:fmnx-io/pack.git
      force: true
      commit: true
      ssh_key:
        from_secret: SSHKEY

  - name: push codeberg mirror
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: git@codeberg.org:fmnx/pack.git
      force: true
      commit: true
      ssh_key:
        from_secret: CBSSHKEY
