run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gas
    - goconst
    - goimports
    - golint
    - govet
    - ineffassign
    - interfacer
    - maligned
    - megacheck
    - structcheck
    - unconvert
    - varcheck
  fast: false

linters-settings:
  maligned:
    suggest-new: true
