# PKGBUILD generated by pack.
# More info at: https://fmnx.io/dev/pack

pkgname="pack"
pkgver="1"
pkgrel="1"
arch=('i686' 'pentium4' 'x86_64' 'arm' 'armv7h' 'armv6h' 'aarch64' 'riscv64')
url="https://fmnx.io/core/pack"

# Edit build dependencies
makedepends=(
  "go"
)

build() {
  cd ..
  # Edit your build scripts after this line
  go build -o pack .
}

package() {
  cd ..
  # Edit file mapping in end system
  declare -A filemap=(
    ["pack"]="/usr/bin/pack"
  )
  # Edit directory mapping in end system
  declare -A dirmap=()
  
  # Process of file installation
  for file in "${!filemap[@]}"
  do 
    install -Dm755 $file $pkgdir${filemap[$file]}
  done
  
  # Process of directory installation
  for dir in "${!dirmap[@]}"
  do 
    cd $dir
    find . -type f -exec install -Dm755 {} $pkgdir${dirmap[$dir]}/{} \;
    cd $srcdir/..
  done
}
