// 2023 FMNX team.
// Use of this code is governed by GNU General Public License.
// Additional information can be found on official web page: https://fmnx.su/
// Contact email: help@fmnx.su

package tmpl

// This package contains string templates for utility command output.
// Output might be modified based on configuration - prettyprint.

const Cobra = `{{if gt (len .Aliases) 0}}Aliases:
{{.NameAndAliases}}{{end}}{{if .HasAvailableSubCommands}}{{$cmds := .Commands}}{{if eq (len .Groups) 0}}Available Commands:{{range $cmds}}{{if (or .IsAvailableCommand (eq .Name "help"))}}
{{rpad .Name .NamePadding }} {{.Short}}{{end}}{{end}}{{else}}{{range $group := .Groups}}

{{.Title}}{{range $cmds}}{{if (and (eq .GroupID $group.ID) (or .IsAvailableCommand (eq .Name "help")))}}
{{rpad .Name .NamePadding }} {{.Short}}{{end}}{{end}}{{end}}{{if not .AllChildCommandsHaveGroup}}

Additional Commands:{{range $cmds}}{{if (and (eq .GroupID "") (or .IsAvailableCommand (eq .Name "help")))}}
{{rpad .Name .NamePadding }} {{.Short}}{{end}}{{end}}{{end}}{{end}}{{end}}{{if .HasAvailableLocalFlags}}{{end}}
`

const PKGBUILD = `# PKGBUILD generated by pack.
# More info at: https://fmnx.su/core/pack

pkgname="%s"
pkgdesc="Something awesome"
pkgver="1"
pkgrel="1"
arch="any"
url="%s"

# Edit runtime dependencies
depends=(
  "python"
  "vlc"
)

# Edit build dependencies
makedepends=(
  "flutter"
  "clang"
  "cmake"
)

build() {
  cd ..
  # Example build command
  make build
}

package() {
  cd ..
  # Example of file installation
  install -Dm755 example $pkgdir/usr/bin/example
  # Example of dir installation
  cd build/bundle && find . -type f -exec install -Dm755 {} $pkgdir/etc/share/example/{} \; && cd $srcdir/..
}
`

const PrettyDesc = `--------------------------------
Name        : %s
Version     : %s
Description : %s
Size        : %s
Url         : %s
BuildDate   : %s
PackName    : %s
PackVersion : %s
PackBranch  : %s
DependsOn   : %s
RequiredBy  : %s
`
