package cmd

import (
	"fmt"
	"strings"

	"fmnx.io/core/pack/print"
	"fmnx.io/core/pack/system"
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(generateCmd)
}

var generateCmd = &cobra.Command{
	Use:     "generate",
	Aliases: []string{"gen", "g"},
	Short:   "📋 generate PKGBUILD",
	Long: `📋 generate PKGBUILD and update README.md with installation helper

This command will generate .pack.yml template and add some lines to README.md
to provide information about installation with pack.`,
	Run: Generate,
}

// Cli command modifying files in workdir for pack compatability.
func Generate(cmd *cobra.Command, args []string) {
	info := GetInstallLink()
	WritePackageBuild(info)
	ModifyReadmeFile(info.Link)
	print.Green("Updated files: ", "PKGBUILD README.md")
}

// Some basic info about repository.
type RepositoryInfo struct {
	ShortName string
	FullName  string
	Link      string
}

// Get information about repository located in current directory.
func GetInstallLink() RepositoryInfo {
	link, err := system.Callf("git config --get remote.origin.url")
	CheckErr(err)
	link = strings.Trim(link, "\n")
	link = strings.ReplaceAll(link, "https://", "")
	link = strings.ReplaceAll(link, "git@", "")
	link = strings.ReplaceAll(link, ":", "/")
	link = strings.ReplaceAll(link, ".git", "")
	splt := strings.Split(link, "/")
	return RepositoryInfo{
		ShortName: splt[len(splt)-1],
		FullName:  link,
		Link:      "https://" + link,
	}
}

// Owerwrite current PKGBUILD file.
func WritePackageBuild(i RepositoryInfo) {
	tmpl := fmt.Sprintf(pkgbuildTemplate, i.ShortName, i.Link)
	err := system.WriteFile("PKGBUILD", tmpl)
	CheckErr(err)
}

// Append some lines to README.md file.
func ModifyReadmeFile(link string) {
	insatllMd := fmt.Sprintf(readmeTemplate, "```", link, "```")
	system.AppendToFile("README.md", insatllMd)
}

const (
	pkgbuildTemplate = `# PKGBUILD generated by pack.
# More info at: https://fmnx.io/core/pack

pkgname="%s"
pkgver="1"
pkgrel="1"
arch=('i686' 'pentium4' 'x86_64' 'arm' 'armv7h' 'armv6h' 'aarch64' 'riscv64')
url="%s"

# Edit runtime dependencies
depends=(
  "python"
  "vlc"
)

# Edit build dependencies
makedepends=(
  "flutter"
  "clang"
  "cmake"
)

build() {
  cd ..
  # Example build command
  make build
}

package() {
  cd ..
  # Example of file installation
  install -Dm755 example $pkgdir/usr/bin/example
  # Example of dir installation
  cd build/bundle && find . -type f -exec install -Dm755 {} $pkgdir/etc/share/example/{} \; && cd $srcdir/..
}
`
	readmeTemplate = `

---

### 📦 Install package with [pack](https://fmnx.io/core/pack):

%s
pack get %s
%s
`
)
